### ISSUE TITLE
Cannot get elevation data from Mapquest API

### ISSUE THREAD

**Issue by john-lee-johnson** [sosna/pinetrail#41]
Hi, thank you for this wonderful resource. I am having trouble getting elevation data from MapQuest, I received an API Key from MapQuest and I have tested that it works by making a request with the key using the example on this [page](https://developer.mapquest.com/documentation/open/elevation-api/elevation-chart/get/). However, pinetrail warns that elevation data could not be found in the response from MapQuest.

Sorry, I know that's not a very helpful description and I'm not sure I can make a reproducible example, but any help would be appreciated.

**Comment by sosna** [comment]
Hi John,

Thanks for your kind words. 

I could reproduce the issue based on the information you provided. I investigated it and, unfortunately, it seems that MapQuest  changed their API. Although their documentation states otherwise, it looks as if the flag outShapeFormat=none is no longer allowed. [Other projects faced the issue](https://sourceforge.net/p/jgpstrackedit/discussion/general/thread/0d07524686/?limit=25#fced), which is how I found out.

I have changed the code accordingly and if you check out the code again and build it as documented, you should now get elevation data (it's working for me now). 

I hope this helps.

Cheers,

Xavier
